---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
# dotfiles_files:
#   - .zshrc
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - zsh-history-substring-search
  - age
  - ansible-lint
  - argon2
  - arkade
  - aspell
  - autoconf
  - azure-cli
  - brotli
  - ca-certificates
  - ccat
  - cfssl
  - chezmoi
  - cjson
  - coreutils
  - curl
  - direnv
  - drone-cli
  - exiftool
  - faas-cli
  - ffind
  - fontconfig
  - fping
  - freetds
  - freetype
  - fzf
  - gd
  - gdbm
  - gettext
  - giflib
  - gmp
  - gnu-sed
  - go
  - helm
  - highway
  - htop
  - jq
  - jsonschema
  - k3d
  - k9s
  - krew
  - kubernetes-cli
  - libarchive
  - libavif
  - libb2
  - libevent
  - libidn2
  - liblinear
  - libnghttp2
  - libpcap
  - libpng
  - libpq
  - libpython-tabulate
  - libsodium
  - libssh2
  - libtiff
  - libtool
  - libunistring
  - libuv
  - libvmaf
  - libwebsockets
  - libyaml
  - libzip
  - lnav
  - lsusb
  - lua@5.3
  - lz4
  - m-cli
  - m4
  - mpdecimal
  - ncdu
  - ncurses
  - nmap
  - oniguruma
  - openexr
  - openssl@1.1
  - openssl@3
  - pkg-config
  - protobuf
  - pwgen
  - pyenv
  - pygments
  - pyyaml
  - readline
  - rtmpdump
  - six
  - skhd
  - stern
  - switch-lan-play
  - the_silver_searcher
  - tidy-html5
  - tig
  - tmux
  - trivy
  - up
  - utf8proc
  - vivid
  - watch
  - webp
  - wget
  - xz
  - chezmoi
  - yabai
  - yamllint
  - z
  - zstd
  - google-cloud-sdk
  - rar

  - wine-stable

  - yabai

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - wireshark
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - licecap
  - sequel-ace
  - slack
  - transmit
  - arduino
  - azure-data-studio
  - bitwarden
  - bluetility
  - darktable
  - discord
  - docker-edge
  - rawtherapee
  - skype
  - slack
  - spectacle
  - steam
  - tripmode
  - vagrant
  - virtualbox
  - visual-studio-code
  - vlc
  - iterm2
  - kindle
  - maccy
  - mark-text
  - mono-mdk-for-visual-studio
  - powershell

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

# osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
